reddit:
  username: UserName
  password: hunter2
  clientId: xxxxxxxx
  clientSecret: yyyyyyy
  database: postgres
postgres:
  host: localhost
  port: 5432
  username: postgres
  password: guest
subreddits:
  - stscardbottest
