reddit:
  username: UserName
  password: hunter2
  clientId: xxxxxxxx
  clientSecret: yyyyyyy
postgres:
  host: localhost
  port: 5432
  username: postgres
  password: guest
  database: postgres
subreddits:
  - stscardbottest
